export const metadata = {
  title: "New Articles",
  description: "Generated by create next app",
};

export default function ArticleNewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <div>
      <h1 className="text-2xl">New Article</h1>
      {children}
    </div>
  );
}
