import Link from "next/link";

export const metadata = {
  title: "Articles",
  description: "Generated by create next app",
};

export default function ArticlesLayout({
  children,
  modalNew,
}: {
  modalNew: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <>
      {modalNew}
      <main className="mx-auto max-w-[1024px] pt-6">
        <div className="flex items-center justify-between border-b pb-4">
          <Link href="/articles">
            <h1 className="text-3xl">Articles</h1>
          </Link>
          <Link href="/articles/new" className="bg-slate-100 py-2 px-4">
            New article
          </Link>
        </div>
        {children}
      </main>
    </>
  );
}
